cache: bundler
sudo: false
script: "bundle exec rake"
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/Gemfile.rails-3.2.22
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-edge
    - gemfile: gemfiles/Gemfile.rails-3.2.22
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-edge
    - rvm: 2.1.7
      gemfile: gemfiles/Gemfile.rails-edge
